### ISSUE TITLE
NewLife.Map.ConvertAsync 实现方式不完整

### ISSUE THREAD

**Issue by wangslsl** [NewLifeX/NewLife.Map#2]
#### 方法实现缺失
定位方法 NewLife.Map.IMap.ConvertAsync

    #region 方法
    /// <summary>异步获取字符串</summary>
    /// <param name="url"></param>
    /// <returns></returns>
    Task<String> GetStringAsync(String url);
    #endregion

按照源码运行，只实现了百度地图，其他几种地图无实现。

#### 期望：
实现其他几种地图的转换

**Comment by nnhy** [comment]
其它地图暂未找到坐标系转换接口。
按计划，将会在基类实现一套网络上找到的方法。
